//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sehirler_yagıslar.DbSehir
{
    using System;
    using System.Collections.Generic;
    
    public partial class rainTable
    {
        public string city { get; set; }
        public Nullable<int> rain { get; set; }
        public string rainMonth { get; set; }
        public string rainYear { get; set; }
        public int rainID { get; set; }
    }
}
